spring:
  application:
    name: SpringDemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.104.172:3306/mybatis
    username: root
    password: 123456

server:
  port: 9090
  servlet:
    context-path: /start

